# Generated by Django 4.1.7 on 2023-02-23 19:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declarationarabe', models.FloatField(blank=True, null=True)),
                ('declarationlatine', models.FloatField(blank=True, null=True)),
                ('classe', models.CharField(blank=True, max_length=200, null=True)),
                ('unite', models.CharField(blank=True, max_length=200, null=True)),
                ('validité', models.DateField(blank=True, default=datetime.datetime(2023, 2, 23, 20, 31, 52, 947264), null=True)),
                ('numero_de_lot', models.IntegerField(blank=True)),
                ('remarque', models.CharField(blank=True, max_length=200, null=True)),
                ('variable', models.BooleanField()),
                ('idClassification', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='article.classification')),
            ],
        ),
    ]
