# Generated by Django 4.1.7 on 2023-02-23 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='validité',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 24, 0, 10, 29, 381872), null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='variable',
            field=models.BooleanField(default=False),
        ),
    ]
