# Generated by Django 4.1.7 on 2023-02-23 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_validité_alter_article_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='numero_de_lot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='validité',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 24, 0, 12, 27, 162658), null=True),
        ),
    ]
