# Generated by Django 4.1.7 on 2023-02-23 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_numero_de_lot_alter_article_validité'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ch',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='validité',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 24, 0, 20, 17, 745069), null=True),
        ),
    ]
