# Generated by Django 4.1.7 on 2023-02-24 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_validité'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='validité',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 24, 8, 20, 32, 602977), null=True),
        ),
    ]
